name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkov:
    name: Checkov (policy gate)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform
          external_checks_dirs: custom_checks
          quiet: true
          soft_fail: false
          check: CKV_AWS_24,CKV_AWS_25,CKV_AWS_53,CKV_AWS_54,CKV_AWS_55,CKV_AWS_56,CKV2_AWS_6,CKV2_AWS_12,CKV_AWS_79,CKV_AWS_88,CKV_AWS_17,CKV_AWS_16,CKV_AWS_60,CKV_AWS_62,CKV_AWS_63,CKV_AWS_286,CKV_AWS_287,CKV_AWS_288,CKV_AWS_289,CKV_AWS_290,CKV_AWS_355,CKV2_AWS_40,CKV_CUSTOM_1

  tfsec:
    name: tfsec (report only)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: terraform
          soft_fail: true
